/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
  }
}
